WITH 
CHILD_LEVEL AS 
(SELECT DIM_KDR_KPL_ORG_HIER_ID, KOSTENPLAATS_KIND, ORGANISATIE_BK_VADER, ORGANISATIE_KIND, ORGANISATIE_BK_KIND, HR_NIVEAU FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC WHERE KOSTENPLAATS_KIND LIKE 'B5%'),
HIERARCHIE AS (
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL0.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, TO_NUMBER('') AS LVL1
, '' AS ORGANISATIE_LVL1
, TO_NUMBER('') AS LVL2
, '' AS ORGANISATIE_LVL2
, TO_NUMBER('') AS LVL3
, '' AS ORGANISATIE_LVL3
, TO_NUMBER('') AS LVL4
, '' AS ORGANISATIE_LVL4
, TO_NUMBER('') AS LVL5
, '' AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
WHERE KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL1.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL1.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL1.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, TO_NUMBER('') AS LVL2
, '' AS ORGANISATIE_LVL2
, TO_NUMBER('') AS LVL3
, '' AS ORGANISATIE_LVL3
, TO_NUMBER('') AS LVL4
, '' AS ORGANISATIE_LVL4
, TO_NUMBER('') AS LVL5
, '' AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0 
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL2.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL2.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL2.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, LVL2.ORGANISATIE_BK_KIND AS LVL2
, LVL2.ORGANISATIE_KIND AS ORGANISATIE_LVL2
, TO_NUMBER('') AS LVL3
, '' AS ORGANISATIE_LVL3
, TO_NUMBER('') AS LVL4
, '' AS ORGANISATIE_LVL4
, TO_NUMBER('') AS LVL5
, '' AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL3.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL3.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL3.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, LVL2.ORGANISATIE_BK_KIND AS LVL2
, LVL2.ORGANISATIE_KIND AS ORGANISATIE_LVL2
, LVL3.ORGANISATIE_BK_KIND AS LVL3
, LVL3.ORGANISATIE_KIND AS ORGANISATIE_LVL3
, TO_NUMBER('') AS LVL4
, '' AS ORGANISATIE_LVL4
, TO_NUMBER('') AS LVL5
, '' AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL4.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL4.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL4.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, LVL2.ORGANISATIE_BK_KIND AS LVL2
, LVL2.ORGANISATIE_KIND AS ORGANISATIE_LVL2
, LVL3.ORGANISATIE_BK_KIND AS LVL3
, LVL3.ORGANISATIE_KIND AS ORGANISATIE_LVL3
, LVL4.ORGANISATIE_BK_KIND AS LVL4
, LVL4.ORGANISATIE_KIND AS ORGANISATIE_LVL4
, TO_NUMBER('') AS LVL5
, '' AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL5.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL5.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL5.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, LVL2.ORGANISATIE_BK_KIND AS LVL2
, LVL2.ORGANISATIE_KIND AS ORGANISATIE_LVL2
, LVL3.ORGANISATIE_BK_KIND AS LVL3
, LVL3.ORGANISATIE_KIND AS ORGANISATIE_LVL3
, LVL4.ORGANISATIE_BK_KIND AS LVL4
, LVL4.ORGANISATIE_KIND AS ORGANISATIE_LVL4
, LVL5.ORGANISATIE_BK_KIND AS LVL5
, LVL5.ORGANISATIE_KIND AS ORGANISATIE_LVL5
, TO_NUMBER('') AS LVL6
, '' AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL5 ON LVL4.ORGANISATIE_BK_KIND = LVL5.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
UNION ALL
SELECT 
  LVL0.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_TOP
, LVL0.HR_NIVEAU AS HR_NIVEAU_TOP
, LVL0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, LVL6.DIM_KDR_KPL_ORG_HIER_ID AS KPLKDR_ID_CHILD
, LVL6.HR_NIVEAU AS HR_NIVEAU_CHILD
, LVL6.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
, LVL0.ORGANISATIE_BK_KIND AS LVL_T 
, LVL0.ORGANISATIE_KIND AS ORGANISATIE_TOP
, LVL1.ORGANISATIE_BK_KIND AS LVL1
, LVL1.ORGANISATIE_KIND AS ORGANISATIE_LVL1
, LVL2.ORGANISATIE_BK_KIND AS LVL2
, LVL2.ORGANISATIE_KIND AS ORGANISATIE_LVL2
, LVL3.ORGANISATIE_BK_KIND AS LVL3
, LVL3.ORGANISATIE_KIND AS ORGANISATIE_LVL3
, LVL4.ORGANISATIE_BK_KIND AS LVL4
, LVL4.ORGANISATIE_KIND AS ORGANISATIE_LVL4
, LVL5.ORGANISATIE_BK_KIND AS LVL5
, LVL5.ORGANISATIE_KIND AS ORGANISATIE_LVL5
, LVL6.ORGANISATIE_BK_KIND AS LVL6
, LVL6.ORGANISATIE_KIND AS ORGANISATIE_LVL6
FROM DMT.DIM_KDR_KPL_ORG_HIER@EBS_ORACLE_1FA_ACC LVL0
INNER JOIN CHILD_LEVEL LVL1 ON LVL0.ORGANISATIE_BK_KIND = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL5 ON LVL4.ORGANISATIE_BK_KIND = LVL5.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL6 ON LVL5.ORGANISATIE_BK_KIND = LVL6.ORGANISATIE_BK_VADER 
WHERE LVL0.KOSTENPLAATS_KIND LIKE 'B5%'
)
SELECT 
 HIERARCHIE.*
,FCT_FAC.DIM_FACTUUR_ID
,FCT_FAC.DIM_GROOTBOEKPERIODE_ID
,FCT_FAC.DIM_KDR_KPL_ORG_HIER_ID
,FCT_FAC.DIM_DIENST_ID
,FCT_FAC.DIM_DATUM_FACTUUR_ID
,FCT_FAC.DIM_DATUM_FACTUUR_ID
,FCT_FAC.DIM_LEVERANCIER_ID
,EXTRACT(YEAR FROM COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM)) AS JAAR
,EXTRACT(MONTH FROM COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM)) AS MAAND_NUMMER
,INITCAP(LOWER(TO_CHAR(COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM), 'MON', 'NLS_DATE_LANGUAGE=DUTCH'))) AS MAAND_NAAM
,INITCAP(LOWER(TO_CHAR(COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM), 'DD-MON', 'NLS_DATE_LANGUAGE=DUTCH'))) AS DD_MON 
,FAC.FACTUURNUMMER
,FAC.AFGESLOTEN_IND
,FAC.BETAALSTATUS
,FAC.FACTUURDATUM
,FAC.ONTVANGSTDATUM
,FAC.SCANDATUM
,FAC.AANMAAKDATUM
,FAC.LAATSTE_BETAALDATUM
,FCT_FAC.AANTAL_DAGEN_OPENSTAAND
,FAC.FACTUUR_MATCH_INKOOPORDER_IND
,FAC.GROOTBOEKDATUM 
,FAC.BETAALTERMIJNDATUM
,FAC.LAATSTE_TERMIJNVERVALDATUM
,FAC.BETAALSTATUS
,FAC.FACTUUR_MATCH_INKOOPORDER_IND
,COALESCE(FAC.ONTVANGSTDATUM,FAC.FACTUURDATUM) + 30 AS VANAF_30_DGN
,CASE WHEN CURRENT_DATE <= ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) AND FAC.AFGESLOTEN_IND = 'NEE' THEN 'NVIN' ELSE NULL END AS FACTUREN_IN_30DGN_NVIN -- NVIN: Niet voldaan (30 dagen nog niet voorbij)
,CASE WHEN CURRENT_DATE > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) AND FAC.AFGESLOTEN_IND = 'NEE' THEN 'NVNA' ELSE NULL END AS FACTUREN_NA_30DGN_NVNA -- NVNA: Niet voldaan (Na 30 dagen voorbij)
,CASE WHEN FAC.LAATSTE_BETAALDATUM <= CURRENT_DATE AND FAC.LAATSTE_BETAALDATUM <= ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) THEN 'VIN' ELSE NULL END AS FACTUREN_IN_30DGN_VIN -- VIN: Voldaan 
,CASE WHEN FAC.LAATSTE_BETAALDATUM <= CURRENT_DATE AND FAC.LAATSTE_BETAALDATUM > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) THEN 'VNA' ELSE NULL END AS FACTUREN_NA_30DGN_VNA 
,CASE WHEN (CASE WHEN CURRENT_DATE > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) AND FAC.AFGESLOTEN_IND = 'NEE' THEN CURRENT_DATE - ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) <= 7 THEN 'NVNA_0_7' ELSE NULL END AS FACTUREN_NA_30DGN_NVNA_0_7  
,CASE WHEN (CASE WHEN CURRENT_DATE > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) AND FAC.AFGESLOTEN_IND = 'NEE' THEN CURRENT_DATE - (COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) BETWEEN 8 AND 14 THEN 'NVNA_8_14' ELSE NULL END AS FACTUREN_NA_30DGN_NVNA_8_14  
,CASE WHEN (CASE WHEN CURRENT_DATE > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) AND FAC.AFGESLOTEN_IND = 'NEE' THEN CURRENT_DATE - (COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) > 14 THEN 'NVNA_G_14' ELSE NULL END AS FACTUREN_NA_30DGN_NVNA_G_14  
,CASE WHEN (CASE WHEN FAC.LAATSTE_BETAALDATUM <= CURRENT_DATE AND FAC.LAATSTE_BETAALDATUM > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) THEN CURRENT_DATE - ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) <= 7 THEN 'VNA_0_7' ELSE NULL END AS FACTUREN_NA_30DGN_VNA_0_7
,CASE WHEN (CASE WHEN FAC.LAATSTE_BETAALDATUM <= CURRENT_DATE AND FAC.LAATSTE_BETAALDATUM > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) THEN CURRENT_DATE - ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) BETWEEN 8 AND 14 THEN 'VNA_8_14' ELSE NULL END AS FACTUREN_NA_30DGN_VNA_8_14 
,CASE WHEN (CASE WHEN FAC.LAATSTE_BETAALDATUM <= CURRENT_DATE AND FAC.LAATSTE_BETAALDATUM > ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) THEN CURRENT_DATE - ( COALESCE(FAC.ONTVANGSTDATUM, FAC.FACTUURDATUM) + 30) ELSE NULL END) <= 7 THEN 'VNA_G_14' ELSE NULL END AS FACTUREN_NA_30DGN_VNA_G_14 
FROM DMT.FCT_FACTUREN_DIENSTEN@EBS_ORACLE_1FA_ACC FCT_FAC 
INNER JOIN DMT.DIM_FACTUUR@EBS_ORACLE_1FA_ACC FAC ON FCT_FAC.DIM_FACTUUR_ID = FAC.DIM_FACTUUR_ID
INNER JOIN DMT.DIM_LEVERANCIER@EBS_ORACLE_1FA_ACC LEV ON FCT_FAC.DIM_LEVERANCIER_ID = LEV.DIM_LEVERANCIER_ID
INNER JOIN HIERARCHIE ON HIERARCHIE.KPLKDR_ID_CHILD = FCT_FAC.DIM_KDR_KPL_ORG_HIER_ID 
WHERE DIM_DIENST_ID = 65 AND AFGESLOTEN_IND = 'NEE'