
WITH 
CHILD_LEVEL AS -- subquery child_level
(SELECT DIM_KDR_KPL_ORG_HIER_ID, KOSTENPLAATS_KIND, ORGANISATIE_BK_VADER, ORGANISATIE_KIND, ORGANISATIE_BK_KIND, HR_NIVEAU FROM DMT.DIM_KDR_KPL_ORG_HIER WHERE KOSTENPLAATS_KIND LIKE 'B5%')
SELECT
  KPLKDR_ID_TOP
, HR_NIVEAU_TOP
, KOSTENPLAATS_TOP
, KPLKDR_ID_CHILD
, HR_NIVEAU_CHILD
, KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, top
, Organisatie_top
, LVL1
, Organisatie_lvl1
, LVL2
, Organisatie_lvl2
, LVL3
, Organisatie_lvl3
, LVL4
, Organisatie_lvl4
, LVL5
, Organisatie_lvl5
, LVL6
, Organisatie_lvl6
FROM
(
-- top lvl
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as top
, lvl0.ORGANISATIE_KIND as Organisatie_top
, to_number('') as LVL1
, '' as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
WHERE KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 1
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl1.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl1.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl1.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0 
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 2
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl2.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 3
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl3.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl3.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl3.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 4
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl4.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl4.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl4.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%'
UNION ALL
-- lvl 5
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl5.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl5.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl5.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 6
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl6.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl6.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl6.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, lvl6.ORGANISATIE_BK_KIND as LVL6
, lvl6.ORGANISATIE_KIND as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl6 on lvl5.ORGANISATIE_BK_KIND = lvl6.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
)
where kplkdr_id_child = 8223
--ORDER BY KPLKDR_ID_TOP, HR_NIVEAU_CHILD, HR_NIVEAU_TOP

