WITH 
CHILD_LEVEL AS -- subquery child_level
(SELECT DIM_KDR_KPL_ORG_HIER_ID, KOSTENPLAATS_KIND, ORGANISATIE_BK_VADER, ORGANISATIE_KIND, ORGANISATIE_BK_KIND, HR_NIVEAU FROM DMT.DIM_KDR_KPL_ORG_HIER WHERE KOSTENPLAATS_KIND LIKE 'B5%'),
BUDGET AS (select 
dim_datum_jaar_id
, dim_dienst_id
, CASE WHEN dim_psb_status_id = 85 THEN 'DIENST AKKOORD' ELSE NULL END DIM_PSB_STATUS
, dim_kdr_kpl_org_hier_id
, jaar_t
, sum(jaar_t_lasten) over (partition by dim_kdr_kpl_org_hier_id, dim_datum_jaar_id) as BUDGET_LASTEN
, sum(jaar_t_baten) over (partition by dim_kdr_kpl_org_hier_id, dim_datum_jaar_id) as BUDGET_BATEN
, sum(jaar_t_saldo) over (partition by dim_kdr_kpl_org_hier_id, dim_datum_jaar_id) as BUDGET_SALDO
from dmt.fct_budgetmutatieregels
where dim_psb_status_id = 85 --Akk. DControl
and dim_dienst_id = 65 -- vooralsnog geen data voor dienst OCW
),
HIERARCHIE AS -- subquery hierarchie 
(SELECT
  KPLKDR_ID_TOP
, HR_NIVEAU_TOP
, KOSTENPLAATS_TOP
, KPLKDR_ID_CHILD
, HR_NIVEAU_CHILD
, KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, top
, Organisatie_top
, LVL1
, Organisatie_lvl1
, LVL2
, Organisatie_lvl2
, LVL3
, Organisatie_lvl3
, LVL4
, Organisatie_lvl4
, LVL5
, Organisatie_lvl5
, LVL6
, Organisatie_lvl6
FROM
(
-- top lvl
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND AS KOSTENPLAATS_TOP
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.KOSTENPLAATS_KIND AS KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as top
, lvl0.ORGANISATIE_KIND as Organisatie_top
, to_number('') as LVL1
, '' as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
WHERE KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 1
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl1.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl1.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl1.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0 
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 2
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl2.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 3
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl3.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl3.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl3.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 4
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl4.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl4.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl4.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%'
UNION ALL
-- lvl 5
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl5.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl5.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl5.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
UNION ALL
-- lvl 6
select 
  lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.KOSTENPLAATS_KIND as KOSTENPLAATS_TOP
, lvl6.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl6.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl6.KOSTENPLAATS_KIND as KOSTENPLAATS_CHILD
-- organisatie namen en organisatie id's
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, lvl6.ORGANISATIE_BK_KIND as LVL6
, lvl6.ORGANISATIE_KIND as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl6 on lvl5.ORGANISATIE_BK_KIND = lvl6.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B5%' 
)
WHERE KPLKDR_ID_TOP = 8313
ORDER BY KPLKDR_ID_TOP, HR_NIVEAU_CHILD, HR_NIVEAU_TOP
) -- einde subquery Hierarchie
--
--
--
-- Begin BudgetUitputting query
SELECT
QY2.GBP_PERIODE_JAAR
,QY2.GBP_MAAND_NUMMER
,QY2.KPLKDR_ID_TOP
,QY2.HR_NIVEAU_TOP
,QY2.KPLKDR_ID_CHILD
,QY2.HR_NIVEAU_CHILD
,QY2.GBP_BEGINDATUM_PERIODE
,QY2.GBP_EINDDATUM_PERIODE
,QY2.FPSB_DIM_DIENST
,BUDGET.DIM_PSB_STATUS
,BUDGET.
,QY2.REALISATIE_LASTEN
,QY2.REALISATIE_BATEN
,QY2.FPSB_OPENSTAANDE_VERPL
,BUDGET.BUDGET_LASTEN
,BUDGET.BUDGET_BATEN
,BUDGET.BUDGET_SALDO
 QY2.*
,BUDGET.*
FROM
(
SELECT DISTINCT
-- QY2
 HIERARCHIE.*
,QY1.FPSB_DIM_GROOTBOEKPERIODE_ID 
,QY1.FPSB_DIM_KDR_KPL_ORG_HIER_ID
--,QY1.FPSB_DIM_BOEKSLEUTEL_ID
,QY1.GBP_PERIODE_JAAR
,QY1.GBP_MAAND_NUMMER
,QY1.GBP_BEGINDATUM_PERIODE
,QY1.GBP_EINDDATUM_PERIODE
,QY1.GBP_CORRECTIEPERIODE_IND
,QY1.FPSB_DIM_DATUM_JAAR_ID
,QY1.FPSB_DIM_DIENST_ID
-- calculaties
,sum(QY1.FPSB_REALISATIE_BATEN) over (PARTITION BY QY1.FPSB_DIM_GROOTBOEKPERIODE_ID ,QY1.FPSB_DIM_KDR_KPL_ORG_HIER_ID) as FPSB_REALISATIE_BATEN
,sum(QY1.FPSB_REALISATIE_LASTEN) over (PARTITION BY QY1.FPSB_DIM_GROOTBOEKPERIODE_ID ,QY1.FPSB_DIM_KDR_KPL_ORG_HIER_ID) AS FPSB_REALISATIE_LASTEN
,sum(QY1.FPSB_OPENSTAANDE_VERPL) over (PARTITION BY QY1.FPSB_DIM_GROOTBOEKPERIODE_ID ,QY1.FPSB_DIM_KDR_KPL_ORG_HIER_ID) AS FPSB_OPENSTAANDE_VERPL
--,QY1.FPSB_OPENSTAANDE_VERPL
--,QY1.FPSB_REALISATIE_LASTEN
--,QY1.FPSB_OPENSTAANDE_VERPL
--
FROM
(
-- QY1: QUERY LEVEL 1 // NODIG VOOR HULPCALC
SELECT
COUNT(FPSB_DIM_GROOTBOEKPERIODE_ID) OVER (PARTITION BY FPSB_DIM_BOEKSLEUTEL_ID, GBP_PERIODE_JAAR, GBP_MAAND_NUMMER) COUNT_
,CASE
-- BIJ DE EERSTE CASE STATEMENT IS GBP_CORRECTIEPERIODE_IND ALTIJD 'NEE', ANDERS IS DIT EEN DATAKWALITEIT ISSUE 
WHEN COUNT(FPSB_DIM_GROOTBOEKPERIODE_ID) OVER (PARTITION BY FPSB_DIM_BOEKSLEUTEL_ID, GBP_PERIODE_JAAR, GBP_MAAND_NUMMER) = 1 then 1 
WHEN COUNT(FPSB_DIM_GROOTBOEKPERIODE_ID) OVER (PARTITION BY FPSB_DIM_BOEKSLEUTEL_ID, GBP_PERIODE_JAAR, GBP_MAAND_NUMMER) = 2 AND GBP_CORRECTIEPERIODE_IND = 'Ja' then 1 ELSE 0 END AS HULPCALC_CORRECTIEPERIODE_IND
,QY0.*
FROM
(
 -- QY0 -BRON QUERY LEVEL 1
select
 FPSB.DIM_GROOTBOEKPERIODE_ID AS FPSB_DIM_GROOTBOEKPERIODE_ID
,FPSB.DIM_KDR_KPL_ORG_HIER_ID AS FPSB_DIM_KDR_KPL_ORG_HIER_ID
,FPSB.DIM_BOEKSLEUTEL_ID AS FPSB_DIM_BOEKSLEUTEL_ID
,GBP.PERIODE_JAAR AS GBP_PERIODE_JAAR
,extract(MONTH from GBP.BEGINDATUM_PERIODE) AS GBP_MAAND_NUMMER
,GBP.begindatum_periode as GBP_BEGINDATUM_PERIODE
,GBP.EINDDATUM_PERIODE AS GBP_EINDDATUM_PERIODE
,GBP.CORRECTIEPERIODE_IND AS GBP_CORRECTIEPERIODE_IND
,FPSB.DIM_DATUM_JAAR_ID AS FPSB_DIM_DATUM_JAAR_ID
,CASE WHEN FPSB.DIM_DIENST_ID = 65 THEN 'OCW' ELSE NULL END AS FPSB_DIM_DIENST
,FPSB.REALISATIE_BATEN AS FPSB_REALISATIE_BATEN
,FPSB.REALISATIE_LASTEN AS FPSB_REALISATIE_LASTEN
,FPSB.VERPLICHTING AS FPSB_OPENSTAANDE_VERPL
--
from dmt.fct_balansregels_psb FPSB 
inner join dmt.dim_grootboekperiode GBP on FPSB.dim_grootboekperiode_id = GBP.dim_grootboekperiode_id
where dim_dienst_id = 65 
) QY0
) QY1
inner join Hierarchie on Hierarchie.kplkdr_id_child = QY1.FPSB_DIM_KDR_KPL_ORG_HIER_ID -- join van de Hierarchie met de dim_kdr_kpl_org_hier_id uit de factBalans
WHERE QY1.HULPCALC_CORRECTIEPERIODE_IND = 1  
) QY2
Left join BUDGET on QY2.FPSB_DIM_KDR_KPL_ORG_HIER_ID = BUDGET.DIM_KDR_KPL_ORG_HIER_ID AND QY2.GBP_PERIODE_JAAR = BUDGET.dim_datum_jaar_id
AND QY2.FPSB_DIM_KDR_KPL_ORG_HIER_ID = 8313
AND QY2.GBP_MAAND_NUMMER = 9