WITH CHILD_LEVEL AS
(SELECT ORGANISATIE_BK_VADER, ORGANISATIE_BK_KIND, HR_NIVEAU FROM DMT.DIM_KDR_KPL_ORG_HIER WHERE KOSTENPLAATS_KIND LIKE 'B%')
SELECT 
 QY1.*
,LVL1.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL1.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
UNION ALL
SELECT 
 QY1.*
,LVL2.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL2.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER
UNION ALL
SELECT 
 QY1.*
,LVL3.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL3.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER
UNION ALL
SELECT 
 QY1.*
,LVL4.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL4.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER
UNION ALL
SELECT 
 QY1.*
,LVL5.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL5.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL5 ON LVL4.ORGANISATIE_BK_KIND = LVL5.ORGANISATIE_BK_VADER
UNION ALL
SELECT 
 QY1.*
,LVL6.ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_CHILD
,LVL6.HR_NIVEAU AS ORGANISATIE_NIVEAU_CHILD
FROM
(
SELECT DISTINCT 
HR_NIVEAU AS QY1_HR_NIVEAU_TOP
,CASE 
    WHEN HR_NIVEAU = 7 THEN 'ORGANISATIE NIVEAU 7' 
    WHEN HR_NIVEAU = 8 THEN 'ORGANISATIE NIVEAU 8'
    WHEN HR_NIVEAU = 9 THEN 'ORGANISATIE NIVEAU 9'
    WHEN HR_NIVEAU = 10 THEN 'ORGANISATIE NIVEAU 10'
    WHEN HR_NIVEAU = 11 THEN 'ORGANISATIE NIVEAU 11'
    WHEN HR_NIVEAU = 12 THEN 'ORGANISATIE NIVEAU 12'
ELSE NULL END AS QY1_ORGANISATIE_NIVEAU_TOP
,ORGANISATIE_BK_KIND AS QY1_ORGANISATIE_BK_TOP
,ORGANISATIE_KIND AS QY1_ORGANISATIE_TOP
FROM DMT.DIM_KDR_KPL_ORG_HIER 
WHERE KOSTENPLAATS_KIND LIKE 'B%' AND ORGANISATIE_BK_VADER IS NOT NULL AND ORGANISATIE_BK_KIND = 4299
) QY1
INNER JOIN CHILD_LEVEL LVL1 ON QY1_ORGANISATIE_BK_TOP = LVL1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL LVL2 ON LVL1.ORGANISATIE_BK_KIND = LVL2.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL3 ON LVL2.ORGANISATIE_BK_KIND = LVL3.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL4 ON LVL3.ORGANISATIE_BK_KIND = LVL4.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL5 ON LVL4.ORGANISATIE_BK_KIND = LVL5.ORGANISATIE_BK_VADER
INNER JOIN CHILD_LEVEL LVL6 ON LVL5.ORGANISATIE_BK_KIND = LVL6.ORGANISATIE_BK_VADER



--========================================================================================
--datum: 22-10-20
--
SELECT
--  case when count(KPLKDR_ID_CHILD) over (partition by KPLKDR_ID_CHILD, HR_NIVEAU) > 1 
--  and (
--      LVL1 is null or 
--      LVL2 is null or
--      LVL3 is null or 
--      LVL4 is null or 
--      LVL5 is null or 
--      LVL6 is null
--      ) then 1 else 0 end as COUNT_
-- , count(KPLKDR_ID_CHILD) over (partition by KPLKDR_ID_CHILD, HR_NIVEAU) as COUNT_2
  KPLKDR_ID_CHILD
, KPLKDR_ID_TOP
--, HR_NIVEAU_CHILD
, HR_NIVEAU_TOP
, top
, Organisatie_top
, LVL1
, Organisatie_lvl1
, LVL2
, Organisatie_lvl2
, LVL3
, Organisatie_lvl3
, LVL4
, Organisatie_lvl4
, LVL5
, Organisatie_lvl5
, LVL6
, Organisatie_lvl6
FROM
(
WITH CHILD_LEVEL AS
(SELECT DIM_KDR_KPL_ORG_HIER_ID, ORGANISATIE_BK_VADER, ORGANISATIE_KIND,ORGANISATIE_BK_KIND, HR_NIVEAU FROM DMT.DIM_KDR_KPL_ORG_HIER WHERE KOSTENPLAATS_KIND LIKE 'B%')
-- top lvl
select 
lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as top
, lvl0.ORGANISATIE_KIND as Organisatie_top
, to_number('') as LVL1
, '' as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
WHERE KOSTENPLAATS_KIND like 'B%' and DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 1
select 
lvl1.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl1.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, to_number('') as LVL2
, '' as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0 
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 2
select 
lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, to_number('') as LVL3
, '' as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 3
select 
lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, to_number('') as LVL4
, '' as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 4
select 
lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, to_number('') as LVL5
, '' as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 5
select 
lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, to_number('') as LVL6
, '' as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
UNION ALL
-- lvl 6
select 
lvl2.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_CHILD
, lvl0.DIM_KDR_KPL_ORG_HIER_ID as KPLKDR_ID_TOP
, lvl0.HR_NIVEAU as HR_NIVEAU_TOP
, lvl2.HR_NIVEAU as HR_NIVEAU_CHILD
, lvl0.ORGANISATIE_BK_KIND as TOP 
, lvl0.ORGANISATIE_KIND as Organisatie_top
, lvl1.ORGANISATIE_BK_KIND as LVL1
, lvl1.ORGANISATIE_KIND as Organisatie_lvl1
, lvl2.ORGANISATIE_BK_KIND as LVL2
, lvl2.ORGANISATIE_KIND as Organisatie_lvl2
, lvl3.ORGANISATIE_BK_KIND as LVL3
, lvl3.ORGANISATIE_KIND as Organisatie_lvl3
, lvl4.ORGANISATIE_BK_KIND as LVL4
, lvl4.ORGANISATIE_KIND as Organisatie_lvl4
, lvl5.ORGANISATIE_BK_KIND as LVL5
, lvl5.ORGANISATIE_KIND as Organisatie_lvl5
, lvl6.ORGANISATIE_BK_KIND as LVL6
, lvl6.ORGANISATIE_KIND as Organisatie_lvl6
--
from DMT.DIM_KDR_KPL_ORG_HIER lvl0
INNER JOIN CHILD_LEVEL lvl1 on lvl0.ORGANISATIE_BK_KIND = lvl1.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl2 on lvl1.ORGANISATIE_BK_KIND = lvl2.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl3 on lvl2.ORGANISATIE_BK_KIND = lvl3.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl4 on lvl3.ORGANISATIE_BK_KIND = lvl4.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl5 on lvl4.ORGANISATIE_BK_KIND = lvl5.ORGANISATIE_BK_VADER 
INNER JOIN CHILD_LEVEL lvl6 on lvl5.ORGANISATIE_BK_KIND = lvl6.ORGANISATIE_BK_VADER 
WHERE lvl0.KOSTENPLAATS_KIND like 'B%' and lvl0.DIM_KDR_KPL_ORG_HIER_ID in (8313, 7023) 
)
ORDER BY KPLKDR_ID_TOP, HR_NIVEAU_CHILD, HR_NIVEAU_TOP 